--- a/Makefile.PL
+++ b/Makefile.PL
@@ -41,9 +41,9 @@
 
 #------------------------------------------------------------------------
 
-our $LATEX    = ttprompt('latex path',    find_program($ENV{PATH}, "latex"));
-our $PDFLATEX = ttprompt('pdflatex path', find_program($ENV{PATH}, "pdflatex"));
-our $DVIPS    = ttprompt('dvips path',    find_program($ENV{PATH}, "dvips"));
+our $LATEX    = '/usr/bin/latex';
+our $PDFLATEX = '/usr/bin/pdflatex';
+our $DVIPS    = '/usr/bin/dvips';
 
 fix_file(catfile('lib','Template','Latex.pm'), '$LATEX',    $LATEX);
 fix_file(catfile('lib','Template','Latex.pm'), '$PDFLATEX', $PDFLATEX);
